import json
from sqlalchemy.orm import Session
from app.models import PackagingMaterial, FoodCommodity, DataSource

# Authoritative scientific data sources tracking
SEED_SOURCES = [
    {
        "source_name": "USDA FoodData Central",
        "organization": "United States Department of Agriculture (USDA)",
        "source_type": "GOVERNMENT_DATABASE",
        "source_url": "https://fdc.nal.usda.gov/",
        "full_citation": "U.S. Department of Agriculture, Agricultural Research Service. FoodData Central, Foundation Foods & Legacy Data, 2019-2024. fdc.nal.usda.gov.",
        "verified_by": "USDA Agricultural Research Service",
        "last_verified": "2024-10"
    },
    {
        "source_name": "UC Davis Postharvest Technology Center",
        "organization": "University of California, Davis - Department of Plant Sciences",
        "source_type": "ACADEMIC_HANDBOOK",
        "source_url": "https://postharvest.ucdavis.edu/Commodity_Resources/Fact_Sheets/",
        "full_citation": "Kader, A.A., Cantwell, M., et al. (2002-2024). Produce Fact Sheets: Recommendations for Maintaining Postharvest Quality. UC Davis Postharvest Technology Center.",
        "verified_by": "UC Davis Postharvest Specialists",
        "last_verified": "2024-05"
    },
    {
        "source_name": "Robertson Food Packaging Handbook",
        "organization": "CRC Press / Taylor & Francis Group",
        "source_type": "ACADEMIC_HANDBOOK",
        "source_url": "https://www.routledge.com/Food-Packaging-Principles-and-Practice/Robertson/p/book/9781439862415",
        "full_citation": "Robertson, G.L. (2012). Food Packaging: Principles and Practice (3rd Edition). CRC Press, Boca Raton, FL. ISBN 9781439862415.",
        "verified_by": "Packaging Science Editorial Board",
        "last_verified": "2023-01"
    },
    {
        "source_name": "Codex Alimentarius International Food Standards",
        "organization": "Joint FAO/WHO Food Standards Programme",
        "source_type": "GOVERNMENT_DATABASE",
        "source_url": "https://www.fao.org/fao-who-codexalimentarius/en/",
        "full_citation": "FAO/WHO Codex Alimentarius Commission. Standards for Processed Foods and General Principles of Food Hygiene (CXS / CXC Series).",
        "verified_by": "Joint FAO/WHO Food Standards Programme",
        "last_verified": "2023-11"
    },
    {
        "source_name": "ASTM International Standards for Barrier Packaging",
        "organization": "ASTM International",
        "source_type": "ASTM_STANDARD",
        "source_url": "https://www.astm.org/",
        "full_citation": "ASTM International Committee F02 on Primary Barrier Packaging & D10 on Packaging. Standard Test Methods & Terminology for Flexible Barrier Materials.",
        "verified_by": "ASTM Committee F02",
        "last_verified": "2024-02"
    },
    {
        "source_name": "FAO Postharvest & Agribusiness Bulletin",
        "organization": "Food and Agriculture Organization of the United Nations",
        "source_type": "GOVERNMENT_DATABASE",
        "source_url": "https://www.fao.org/post-harvest-compendium/en/",
        "full_citation": "FAO (2018). Post-harvest management and packaging of agricultural produce in developing countries. FAO Agricultural Services Bulletin.",
        "verified_by": "FAO Agro-Industries Division",
        "last_verified": "2023-08"
    }
]

# Curated catalog of 15 packaging materials with qualitative barrier categories.
# In accordance with project integrity rules, all items are tagged 'DEMO DATA' 
# until certified individually against lab testing or verified primary literature.
SEED_MATERIALS = [
    {
        "material_code": "LDPE",
        "name": "Low-Density Polyethylene (LDPE)",
        "material_type": "Mono-Polymer",
        "oxygen_barrier": "VERY_LOW",
        "moisture_barrier": "MEDIUM",
        "sealability": "EXCELLENT",
        "mechanical_strength": "MEDIUM",
        "fat_oil_resistance": "FAIR",
        "temp_min_c": -40.0,
        "temp_max_c": 80.0,
        "storage_compatibility": "Ambient, Refrigerated, Frozen",
        "light_barrier": "TRANSPARENT",
        "recyclability": "HIGHLY_RECYCLABLE",
        "biodegradability": False,
        "relative_cost_category": "LOW",
        "relative_cost_index": 1.0,
        "is_breathable": False,
        "layers_json": json.dumps([
            {"layer_name": "LDPE Monofilm", "typical_thickness_microns": 50, "purpose": "Moisture barrier & heat seal layer"}
        ]),
        "suitable_food_categories": "General dry goods, fresh produce liners, bread, frozen poultry",
        "source_name": "Robertson Food Packaging Handbook",
        "source_url": "https://www.routledge.com/Food-Packaging-Principles-and-Practice/Robertson/p/book/9781439862415",
        "source_reference": "Robertson (2012), Ch. 2: Polyolefins and Extrusion Films",
        "source_citation": "Robertson, G.L. (2012). Food Packaging: Principles and Practice. CRC Press.",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "material_code": "HDPE",
        "name": "High-Density Polyethylene (HDPE)",
        "material_type": "Mono-Polymer",
        "oxygen_barrier": "LOW",
        "moisture_barrier": "HIGH",
        "sealability": "GOOD",
        "mechanical_strength": "HIGH",
        "fat_oil_resistance": "GOOD",
        "temp_min_c": -50.0,
        "temp_max_c": 105.0,
        "storage_compatibility": "Ambient, Refrigerated, Frozen",
        "light_barrier": "SEMI_OPAQUE",
        "recyclability": "HIGHLY_RECYCLABLE",
        "biodegradability": False,
        "relative_cost_category": "LOW",
        "relative_cost_index": 1.2,
        "is_breathable": False,
        "layers_json": json.dumps([
            {"layer_name": "HDPE Film", "typical_thickness_microns": 45, "purpose": "Stiffness, puncture and moisture barrier"}
        ]),
        "suitable_food_categories": "Cereal bag-in-box liners, dairy bottles, frozen foods",
        "source_name": "Robertson Food Packaging Handbook",
        "source_url": "https://www.routledge.com/Food-Packaging-Principles-and-Practice/Robertson/p/book/9781439862415",
        "source_reference": "Robertson (2012), Ch. 2: High-Density Polyethylene Properties",
        "source_citation": "Robertson, G.L. (2012). Food Packaging: Principles and Practice. CRC Press.",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "material_code": "PP",
        "name": "Cast Polypropylene (CPP)",
        "material_type": "Mono-Polymer",
        "oxygen_barrier": "LOW",
        "moisture_barrier": "MEDIUM",
        "sealability": "EXCELLENT",
        "mechanical_strength": "MEDIUM",
        "fat_oil_resistance": "GOOD",
        "temp_min_c": 0.0,
        "temp_max_c": 125.0,
        "storage_compatibility": "Ambient, Refrigerated",
        "light_barrier": "TRANSPARENT",
        "recyclability": "HIGHLY_RECYCLABLE",
        "biodegradability": False,
        "relative_cost_category": "LOW",
        "relative_cost_index": 1.1,
        "is_breathable": False,
        "layers_json": json.dumps([
            {"layer_name": "CPP Film", "typical_thickness_microns": 35, "purpose": "High-clarity heat sealable layer"}
        ]),
        "suitable_food_categories": "Bakery, confectionary, retorting base layer",
        "source_name": "ASTM International Standards for Barrier Packaging",
        "source_url": "https://www.astm.org/",
        "source_reference": "ASTM D882 / Modern Plastics Handbook, McGraw-Hill",
        "source_citation": "Modern Plastics Handbook, McGraw-Hill.",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "material_code": "BOPP",
        "name": "Biaxially Oriented Polypropylene (BOPP)",
        "material_type": "Oriented Film",
        "oxygen_barrier": "LOW",
        "moisture_barrier": "HIGH",
        "sealability": "FAIR",
        "mechanical_strength": "HIGH",
        "fat_oil_resistance": "GOOD",
        "temp_min_c": -10.0,
        "temp_max_c": 120.0,
        "storage_compatibility": "Ambient, Refrigerated",
        "light_barrier": "TRANSPARENT",
        "recyclability": "RECYCLABLE",
        "biodegradability": False,
        "relative_cost_category": "MEDIUM",
        "relative_cost_index": 1.8,
        "is_breathable": False,
        "layers_json": json.dumps([
            {"layer_name": "BOPP Film", "typical_thickness_microns": 25, "purpose": "High tensile strength, print surface & moisture barrier"}
        ]),
        "suitable_food_categories": "Crisp snacks, biscuits, confectionery overwrap",
        "source_name": "Robertson Food Packaging Handbook",
        "source_url": "https://www.routledge.com/Food-Packaging-Principles-and-Practice/Robertson/p/book/9781439862415",
        "source_reference": "Packaging Technology and Engineering, Donald L. Abbott",
        "source_citation": "Packaging Technology and Engineering, Donald L. Abbott.",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "material_code": "PET",
        "name": "Polyethylene Terephthalate Film (BOPET)",
        "material_type": "Polyester Film",
        "oxygen_barrier": "MEDIUM",
        "moisture_barrier": "MEDIUM",
        "sealability": "POOR",
        "mechanical_strength": "VERY_HIGH",
        "fat_oil_resistance": "EXCELLENT",
        "temp_min_c": -60.0,
        "temp_max_c": 180.0,
        "storage_compatibility": "Ambient, Refrigerated, Frozen",
        "light_barrier": "TRANSPARENT",
        "recyclability": "HIGHLY_RECYCLABLE",
        "biodegradability": False,
        "relative_cost_category": "MEDIUM",
        "relative_cost_index": 2.0,
        "is_breathable": False,
        "layers_json": json.dumps([
            {"layer_name": "BOPET Outer Layer", "typical_thickness_microns": 12, "purpose": "Thermal resistance, dimensional stability & printing"}
        ]),
        "suitable_food_categories": "Outer web for retort pouches, roasted nuts, coffee",
        "source_name": "ASTM International Standards for Barrier Packaging",
        "source_url": "https://www.astm.org/",
        "source_reference": "Polymer Handbook, Brandrup et al.",
        "source_citation": "Polymer Handbook, Brandrup et al.",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "material_code": "MET_BOPP",
        "name": "Metallized BOPP Laminate (BOPP/Met-BOPP/PE)",
        "material_type": "Metallized Film",
        "oxygen_barrier": "HIGH",
        "moisture_barrier": "VERY_HIGH",
        "sealability": "GOOD",
        "mechanical_strength": "HIGH",
        "fat_oil_resistance": "EXCELLENT",
        "temp_min_c": -10.0,
        "temp_max_c": 115.0,
        "storage_compatibility": "Ambient, Refrigerated",
        "light_barrier": "OPAQUE",
        "recyclability": "DIFFICULT_MULTI_MATERIAL",
        "biodegradability": False,
        "relative_cost_category": "MEDIUM",
        "relative_cost_index": 2.4,
        "is_breathable": False,
        "layers_json": json.dumps([
            {"layer_name": "Clear BOPP Outer", "typical_thickness_microns": 18, "purpose": "Glossy print carrier"},
            {"layer_name": "Vacuum Metallized BOPP", "typical_thickness_microns": 15, "purpose": "Light, oxygen & water vapor barrier"},
            {"layer_name": "LLDPE Sealant Liner", "typical_thickness_microns": 30, "purpose": "Hermetic seal & puncture resistance"}
        ]),
        "suitable_food_categories": "Fried potato chips, extruded snacks, spices, milk powder",
        "source_name": "Robertson Food Packaging Handbook",
        "source_url": "https://www.routledge.com/Food-Packaging-Principles-and-Practice/Robertson/p/book/9781439862415",
        "source_reference": "Robertson (2012), Ch. 7: Metallized and Barrier Films",
        "source_citation": "Robertson, G.L. (2012). Food Packaging: Principles and Practice. CRC Press.",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "material_code": "EVOH_COEX",
        "name": "EVOH High-Barrier Coextrusion (PE/EVOH/PE)",
        "material_type": "Barrier Multi-Layer",
        "oxygen_barrier": "VERY_HIGH",
        "moisture_barrier": "MEDIUM",
        "sealability": "GOOD",
        "mechanical_strength": "HIGH",
        "fat_oil_resistance": "EXCELLENT",
        "temp_min_c": -30.0,
        "temp_max_c": 100.0,
        "storage_compatibility": "Ambient, Refrigerated, Frozen",
        "light_barrier": "SEMI_OPAQUE",
        "recyclability": "RECYCLABLE",
        "biodegradability": False,
        "relative_cost_category": "HIGH",
        "relative_cost_index": 3.5,
        "is_breathable": False,
        "layers_json": json.dumps([
            {"layer_name": "PE Protective Skin", "typical_thickness_microns": 25, "purpose": "Moisture shield protecting EVOH"},
            {"layer_name": "EVOH Core Layer", "typical_thickness_microns": 5, "purpose": "Ultra-high oxygen & aroma barrier"},
            {"layer_name": "PE Sealant Inner", "typical_thickness_microns": 30, "purpose": "Food contact & heat seal"}
        ]),
        "suitable_food_categories": "Processed meats, fresh cheese, chilled pasta, fruit juices",
        "source_name": "ASTM International Standards for Barrier Packaging",
        "source_url": "https://www.eval.kuraray.com/",
        "source_reference": "Kuraray EVAL Technical Manual for Gas Barrier Polymers",
        "source_citation": "Kuraray EVAL Technical Manual for Gas Barrier Polymers.",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "material_code": "ALU_LAMINATE",
        "name": "Triplex Foil Laminate (PET/Alu Foil/PE)",
        "material_type": "Multi-Layer Laminate",
        "oxygen_barrier": "VERY_HIGH",
        "moisture_barrier": "VERY_HIGH",
        "sealability": "EXCELLENT",
        "mechanical_strength": "VERY_HIGH",
        "fat_oil_resistance": "EXCELLENT",
        "temp_min_c": -50.0,
        "temp_max_c": 130.0,
        "storage_compatibility": "Ambient, Refrigerated, Frozen",
        "light_barrier": "OPAQUE",
        "recyclability": "DIFFICULT_MULTI_MATERIAL",
        "biodegradability": False,
        "relative_cost_category": "VERY_HIGH",
        "relative_cost_index": 4.8,
        "is_breathable": False,
        "layers_json": json.dumps([
            {"layer_name": "PET Outer Web", "typical_thickness_microns": 12, "purpose": "Tear resistance & reverse print"},
            {"layer_name": "Aluminum Foil", "typical_thickness_microns": 9, "purpose": "Extremely high barrier to gas, moisture & light"},
            {"layer_name": "LDPE Seal Layer", "typical_thickness_microns": 50, "purpose": "Hermetic seal & food-contact barrier"}
        ]),
        "suitable_food_categories": "Retort meals, infant formula, coffee beans, emergency rations",
        "source_name": "Robertson Food Packaging Handbook",
        "source_url": "https://www.routledge.com/Food-Packaging-Principles-and-Practice/Robertson/p/book/9781439862415",
        "source_reference": "Robertson (2012), Ch. 7: Triplex Barrier Laminates",
        "source_citation": "Robertson, G.L. (2012). Food Packaging: Principles and Practice. CRC Press.",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "material_code": "PAPER_PE",
        "name": "Extrusion-Coated Paper (Kraft Paper / PE)",
        "material_type": "Cellulosic/Polymer",
        "oxygen_barrier": "VERY_LOW",
        "moisture_barrier": "MEDIUM",
        "sealability": "GOOD",
        "mechanical_strength": "MEDIUM",
        "fat_oil_resistance": "FAIR",
        "temp_min_c": -10.0,
        "temp_max_c": 90.0,
        "storage_compatibility": "Ambient",
        "light_barrier": "OPAQUE",
        "recyclability": "RECYCLABLE",
        "biodegradability": False,
        "relative_cost_category": "LOW",
        "relative_cost_index": 1.4,
        "is_breathable": False,
        "layers_json": json.dumps([
            {"layer_name": "Bleached Kraft Paper", "typical_thickness_microns": 65, "purpose": "Bioderived structural stiffness & print"},
            {"layer_name": "PE Extrusion Coating", "typical_thickness_microns": 15, "purpose": "Heat sealability & grease resistance"}
        ]),
        "suitable_food_categories": "Flour bags, dry grains, sugar, fast-food dry wraps",
        "source_name": "Robertson Food Packaging Handbook",
        "source_url": "https://www.routledge.com/Handbook-of-Paper-and-Paperboard-Packaging-Technology/Kirwan/p/book/9781405125383",
        "source_reference": "Handbook of Paper and Paperboard Packaging Technology, Mark J. Kirwan",
        "source_citation": "Handbook of Paper and Paperboard Packaging Technology, Mark J. Kirwan.",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "material_code": "PLA",
        "name": "Polylactic Acid Bio-Film (PLA)",
        "material_type": "Bio-Plastic",
        "oxygen_barrier": "MEDIUM",
        "moisture_barrier": "LOW",
        "sealability": "FAIR",
        "mechanical_strength": "HIGH",
        "fat_oil_resistance": "GOOD",
        "temp_min_c": 0.0,
        "temp_max_c": 55.0,
        "storage_compatibility": "Ambient, Refrigerated",
        "light_barrier": "TRANSPARENT",
        "recyclability": "COMPOSTABLE",
        "biodegradability": True,
        "relative_cost_category": "HIGH",
        "relative_cost_index": 3.2,
        "is_breathable": False,
        "layers_json": json.dumps([
            {"layer_name": "Bio-based PLA Film", "typical_thickness_microns": 30, "purpose": "Rigid biodegradable film"}
        ]),
        "suitable_food_categories": "Fresh salads, short-shelf-life bakery, dry pulses",
        "source_name": "ASTM International Standards for Barrier Packaging",
        "source_url": "https://www.natureworksllc.com/",
        "source_reference": "NatureWorks Ingeo Technical Product Bulletin & Specifications",
        "source_citation": "NatureWorks Ingeo Technical Product Bulletin & Specifications.",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "material_code": "PBAT_PLA_BLEND",
        "name": "PBAT / PLA Compostable Bio-Blend",
        "material_type": "Bio-Plastic",
        "oxygen_barrier": "LOW",
        "moisture_barrier": "LOW",
        "sealability": "GOOD",
        "mechanical_strength": "MEDIUM",
        "fat_oil_resistance": "FAIR",
        "temp_min_c": -10.0,
        "temp_max_c": 60.0,
        "storage_compatibility": "Ambient, Refrigerated",
        "light_barrier": "SEMI_OPAQUE",
        "recyclability": "COMPOSTABLE",
        "biodegradability": True,
        "relative_cost_category": "HIGH",
        "relative_cost_index": 3.6,
        "is_breathable": False,
        "layers_json": json.dumps([
            {"layer_name": "PBAT/PLA Flexible Film", "typical_thickness_microns": 35, "purpose": "Tough flexible home-compostable film"}
        ]),
        "suitable_food_categories": "Organic fruits, vegetables, dry tea bags",
        "source_name": "ASTM International Standards for Barrier Packaging",
        "source_url": "https://www.biopolymers.basf.com/",
        "source_reference": "BASF Ecovio Biopolymers Technical Data Sheets",
        "source_citation": "BASF Ecovio Biopolymers Technical Data Sheets.",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "material_code": "MICRO_PERF_PE",
        "name": "Laser Micro-Perforated Breathable Film",
        "material_type": "Perforated Film",
        "oxygen_barrier": "VERY_LOW",
        "moisture_barrier": "LOW",
        "sealability": "EXCELLENT",
        "mechanical_strength": "MEDIUM",
        "fat_oil_resistance": "POOR",
        "temp_min_c": 0.0,
        "temp_max_c": 60.0,
        "storage_compatibility": "Refrigerated, Ambient",
        "light_barrier": "TRANSPARENT",
        "recyclability": "HIGHLY_RECYCLABLE",
        "biodegradability": False,
        "relative_cost_category": "MEDIUM",
        "relative_cost_index": 2.2,
        "is_breathable": True,
        "layers_json": json.dumps([
            {"layer_name": "Micro-perforated LLDPE", "typical_thickness_microns": 30, "purpose": "Controlled respiration gas exchange (50µm holes)"}
        ]),
        "suitable_food_categories": "Fresh berries, mushrooms, broccoli, high-respiration produce",
        "source_name": "FAO Postharvest & Agribusiness Bulletin",
        "source_url": "https://www.fao.org/post-harvest-compendium/en/",
        "source_reference": "Postharvest Biology and Technology of Tropical Produce, FAO Agricultural Bulletin",
        "source_citation": "Postharvest Biology and Technology of Tropical Produce, FAO Agricultural Bulletin.",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "material_code": "MET_PET",
        "name": "Metallized Polyester Laminate (PET/Met-PET/PE)",
        "material_type": "Metallized Laminate",
        "oxygen_barrier": "HIGH",
        "moisture_barrier": "HIGH",
        "sealability": "GOOD",
        "mechanical_strength": "HIGH",
        "fat_oil_resistance": "EXCELLENT",
        "temp_min_c": -20.0,
        "temp_max_c": 120.0,
        "storage_compatibility": "Ambient, Refrigerated",
        "light_barrier": "OPAQUE",
        "recyclability": "DIFFICULT_MULTI_MATERIAL",
        "biodegradability": False,
        "relative_cost_category": "MEDIUM",
        "relative_cost_index": 2.6,
        "is_breathable": False,
        "layers_json": json.dumps([
            {"layer_name": "PET Outer Web", "typical_thickness_microns": 12, "purpose": "Reverse print surface & puncture resistance"},
            {"layer_name": "Vacuum Metallized PET", "typical_thickness_microns": 12, "purpose": "High aluminum vapor barrier to light, aroma & gas"},
            {"layer_name": "LLDPE Sealant", "typical_thickness_microns": 40, "purpose": "Hermetic seal & food-grade contact layer"}
        ]),
        "suitable_food_categories": "Coffee, spices, nuts, dried fruits, premium snacks",
        "source_name": "Robertson Food Packaging Handbook",
        "source_url": "https://www.routledge.com/Food-Packaging-Principles-and-Practice/Robertson/p/book/9781439862415",
        "source_reference": "Robertson (2012), Ch. 7: Metallized and Barrier Films",
        "source_citation": "Robertson, G.L. (2012). Food Packaging: Principles and Practice. CRC Press.",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "material_code": "PA_EVOH_PE_COEX",
        "name": "7-Layer High-Barrier Coextrusion (PA/EVOH/PE)",
        "material_type": "Barrier Multi-Layer",
        "oxygen_barrier": "VERY_HIGH",
        "moisture_barrier": "HIGH",
        "sealability": "EXCELLENT",
        "mechanical_strength": "VERY_HIGH",
        "fat_oil_resistance": "EXCELLENT",
        "temp_min_c": -40.0,
        "temp_max_c": 100.0,
        "storage_compatibility": "Ambient, Refrigerated, Frozen",
        "light_barrier": "TRANSPARENT",
        "recyclability": "RECYCLABLE",
        "biodegradability": False,
        "relative_cost_category": "HIGH",
        "relative_cost_index": 3.8,
        "is_breathable": False,
        "layers_json": json.dumps([
            {"layer_name": "Polyamide (Nylon-6) Outer", "typical_thickness_microns": 20, "purpose": "Puncture resistance & thermoformability"},
            {"layer_name": "Tie Resin", "typical_thickness_microns": 5, "purpose": "Polyolefin-polyamide compatibilizer"},
            {"layer_name": "EVOH Core Barrier", "typical_thickness_microns": 5, "purpose": "Ultra-low oxygen transmission rate"},
            {"layer_name": "Tie Resin", "typical_thickness_microns": 5, "purpose": "Polyolefin-EVOH compatibilizer"},
            {"layer_name": "LLDPE / mLLDPE Inner", "typical_thickness_microns": 45, "purpose": "Moisture seal, low seal initiation temp & drop impact"}
        ]),
        "suitable_food_categories": "Processed meats, cheese, modified atmosphere packaging, chilled ready meals",
        "source_name": "ASTM International Standards for Barrier Packaging",
        "source_url": "https://www.eval.kuraray.com/",
        "source_reference": "Kuraray Technical Manual: 7-Layer PA/EVOH/PE Blown Film Formulations & ASTM F1927",
        "source_citation": "ASTM F1927 / Kuraray EVAL Technical Coextrusion Bulletin.",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "material_code": "NATUREFLEX_CELLULOSE",
        "name": "NatureFlex Bio-Cellulose Film",
        "material_type": "Bio-Cellulosic",
        "oxygen_barrier": "HIGH",
        "moisture_barrier": "MEDIUM",
        "sealability": "GOOD",
        "mechanical_strength": "MEDIUM",
        "fat_oil_resistance": "GOOD",
        "temp_min_c": -10.0,
        "temp_max_c": 75.0,
        "storage_compatibility": "Ambient, Refrigerated",
        "light_barrier": "TRANSPARENT",
        "recyclability": "COMPOSTABLE",
        "biodegradability": True,
        "relative_cost_category": "HIGH",
        "relative_cost_index": 3.4,
        "is_breathable": False,
        "layers_json": json.dumps([
            {"layer_name": "Regenerated Wood-Pulp Cellulose Film", "typical_thickness_microns": 20, "purpose": "Sustainably sourced FSC-certified renewable cellulose base"},
            {"layer_name": "Bio-Polymer Barrier Coating", "typical_thickness_microns": 3, "purpose": "Moisture barrier & heat sealability"}
        ]),
        "suitable_food_categories": "Organic dry goods, artisan chocolates, confectionery, premium tea bags",
        "source_name": "ASTM International Standards for Barrier Packaging",
        "source_url": "https://www.futamuragroup.com/en/divisions/cellulose-films/products/natureflex/",
        "source_reference": "NatureFlex NK / NVR Renewable & Home Compostable Packaging Specifications & ASTM D6400",
        "source_citation": "Futamura NatureFlex Technical Data Sheets & ASTM D6400 Certification.",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    }
]

# Curated catalog of 20 food commodities (10 Processed + 10 Fresh Produce)
# In accordance with project integrity rules, all items are tagged 'DEMO DATA'
# until certified individually against lab testing or verified primary literature.
SEED_COMMODITIES = [
    # A. Processed / Packaged Foods (10 items)
    {
        "name": "Potato Chips",
        "category": "Snacks",
        "standard_moisture_percent": 1.8,
        "standard_fat_percent": 34.5,
        "standard_ph": 6.2,
        "oxygen_sensitivity": "VERY_HIGH",
        "moisture_sensitivity": "VERY_HIGH",
        "light_sensitivity": "HIGH",
        "typical_storage_type": "Ambient",
        "is_fresh_produce": False,
        "respiration_category": "NONE",
        "map_suitable": False,
        "recommended_gas_mix": "Flush with 99.5% N2 to prevent lipid oxidation and preserve crispness",
        "source_name": "USDA FoodData Central",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/19411",
        "source_reference": "NDB #19411 - Potato chips, made from dried potatoes, plain",
        "source_citation": "USDA FoodData Central Foundation Foods (NDB #19411)",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "name": "Biscuits",
        "category": "Bakery / Confectionery",
        "standard_moisture_percent": 3.5,
        "standard_fat_percent": 16.0,
        "standard_ph": 6.5,
        "oxygen_sensitivity": "MEDIUM",
        "moisture_sensitivity": "VERY_HIGH",
        "light_sensitivity": "MEDIUM",
        "typical_storage_type": "Ambient",
        "is_fresh_produce": False,
        "respiration_category": "NONE",
        "map_suitable": False,
        "recommended_gas_mix": "Ambient moisture-tight packaging or dry nitrogen flush",
        "source_name": "USDA FoodData Central",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/172784",
        "source_reference": "NDB #18029 - Cookies, plain / tea biscuits",
        "source_citation": "USDA FoodData Central Foundation Foods (NDB #18029)",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "name": "Bread",
        "category": "Bakery",
        "standard_moisture_percent": 36.0,
        "standard_fat_percent": 3.2,
        "standard_ph": 5.5,
        "oxygen_sensitivity": "MEDIUM",
        "moisture_sensitivity": "MEDIUM",
        "light_sensitivity": "LOW",
        "typical_storage_type": "Ambient",
        "is_fresh_produce": False,
        "respiration_category": "NONE",
        "map_suitable": True,
        "recommended_gas_mix": "60-100% CO2, balance N2 to retard mold growth and extend shelf life",
        "source_name": "USDA FoodData Central",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/1100552",
        "source_reference": "FDC ID #1100552 - Bread, white / whole wheat",
        "source_citation": "USDA FoodData Central (FDC ID #1100552) & Robertson Food Packaging",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "name": "Flour",
        "category": "Grains / Milling",
        "standard_moisture_percent": 12.5,
        "standard_fat_percent": 1.5,
        "standard_ph": 6.3,
        "oxygen_sensitivity": "LOW",
        "moisture_sensitivity": "HIGH",
        "light_sensitivity": "LOW",
        "typical_storage_type": "Ambient",
        "is_fresh_produce": False,
        "respiration_category": "NONE",
        "map_suitable": False,
        "recommended_gas_mix": "Ambient packaging with moisture, vapor, and insect barriers",
        "source_name": "USDA FoodData Central",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/20080",
        "source_reference": "NDB #20080 - Wheat flour, whole-grain",
        "source_citation": "USDA FoodData Central Wheat Flour Whole Grain (NDB #20080)",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "name": "Rice",
        "category": "Grains / Staples",
        "standard_moisture_percent": 13.0,
        "standard_fat_percent": 0.7,
        "standard_ph": 6.5,
        "oxygen_sensitivity": "LOW",
        "moisture_sensitivity": "HIGH",
        "light_sensitivity": "LOW",
        "typical_storage_type": "Ambient",
        "is_fresh_produce": False,
        "respiration_category": "NONE",
        "map_suitable": False,
        "recommended_gas_mix": "Ambient dry or vacuum packaging; CO2 flush for long-term grain weevil control",
        "source_name": "USDA FoodData Central",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/169756",
        "source_reference": "NDB #20048 - Rice, white, long-grain, regular, raw",
        "source_citation": "USDA FoodData Central Foundation Foods (NDB #20048)",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "name": "Spices",
        "category": "Spices / Condiments",
        "standard_moisture_percent": 9.0,
        "standard_fat_percent": 12.0,
        "standard_ph": 5.8,
        "oxygen_sensitivity": "HIGH",
        "moisture_sensitivity": "HIGH",
        "light_sensitivity": "VERY_HIGH",
        "typical_storage_type": "Ambient",
        "is_fresh_produce": False,
        "respiration_category": "NONE",
        "map_suitable": False,
        "recommended_gas_mix": "Light-opaque high-barrier hermetic seal with nitrogen flush",
        "source_name": "Codex Alimentarius International Food Standards",
        "source_url": "https://www.fao.org/fao-who-codexalimentarius/standards/en/",
        "source_reference": "Codex Standard for Spices and Culinary Herbs (CXS 342-2021)",
        "source_citation": "Codex Alimentarius Standard for Spices and Culinary Herbs (CXS 342-2021)",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "name": "Coffee",
        "category": "Beverages / Roasts",
        "standard_moisture_percent": 2.5,
        "standard_fat_percent": 14.5,
        "standard_ph": 5.2,
        "oxygen_sensitivity": "VERY_HIGH",
        "moisture_sensitivity": "VERY_HIGH",
        "light_sensitivity": "VERY_HIGH",
        "typical_storage_type": "Ambient",
        "is_fresh_produce": False,
        "respiration_category": "NONE",
        "map_suitable": True,
        "recommended_gas_mix": "100% N2 flush with one-way degassing valve to vent CO2 outgassing",
        "source_name": "Robertson Food Packaging Handbook",
        "source_url": "https://www.routledge.com/Food-Packaging-Principles-and-Practice/Robertson/p/book/9781439862415",
        "source_reference": "Robertson (2012), Ch. 14: Coffee Packaging and Degassing",
        "source_citation": "Robertson, G.L. (2012). Food Packaging: Principles and Practice. CRC Press.",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "name": "Tea",
        "category": "Beverages / Leaves",
        "standard_moisture_percent": 5.0,
        "standard_fat_percent": 2.0,
        "standard_ph": 5.5,
        "oxygen_sensitivity": "HIGH",
        "moisture_sensitivity": "VERY_HIGH",
        "light_sensitivity": "HIGH",
        "typical_storage_type": "Ambient",
        "is_fresh_produce": False,
        "respiration_category": "NONE",
        "map_suitable": False,
        "recommended_gas_mix": "Hermetic dry seal with foil barrier to block moisture and extraneous odors",
        "source_name": "Codex Alimentarius International Food Standards",
        "source_url": "https://www.fao.org/fao-who-codexalimentarius/standards/en/",
        "source_reference": "ISO 3720: Black tea -- Specification and moisture limits",
        "source_citation": "ISO 3720 / Indian Tea Board Packaging Specifications",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "name": "Nuts",
        "category": "Snacks / Dry Fruits",
        "standard_moisture_percent": 3.0,
        "standard_fat_percent": 50.0,
        "standard_ph": 6.4,
        "oxygen_sensitivity": "VERY_HIGH",
        "moisture_sensitivity": "HIGH",
        "light_sensitivity": "HIGH",
        "typical_storage_type": "Ambient",
        "is_fresh_produce": False,
        "respiration_category": "NONE",
        "map_suitable": False,
        "recommended_gas_mix": "Nitrogen flush (< 1% residual O2) with vacuum or gas-tight packaging",
        "source_name": "USDA FoodData Central",
        "source_url": "https://fdc.nal.usda.gov/fdc-app.html#/food-details/170567",
        "source_reference": "NDB #12061 - Nuts, almonds / cashew nuts",
        "source_citation": "USDA FoodData Central Foundation Foods (NDB #12061)",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "name": "Milk Powder",
        "category": "Dairy / Powders",
        "standard_moisture_percent": 3.5,
        "standard_fat_percent": 26.5,
        "standard_ph": 6.6,
        "oxygen_sensitivity": "VERY_HIGH",
        "moisture_sensitivity": "VERY_HIGH",
        "light_sensitivity": "VERY_HIGH",
        "typical_storage_type": "Ambient",
        "is_fresh_produce": False,
        "respiration_category": "NONE",
        "map_suitable": False,
        "recommended_gas_mix": "Hermetic seal with N2/CO2 inert gas flush (< 2% O2 headspace)",
        "source_name": "Codex Alimentarius International Food Standards",
        "source_url": "https://www.fao.org/fao-who-codexalimentarius/standards/en/",
        "source_reference": "Codex Standard for Milk Powders and Cream Powder (CXS 207-1999)",
        "source_citation": "Codex Alimentarius Standard for Milk Powders (CXS 207-1999)",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },

    # B. Fresh Produce (10 items)
    {
        "name": "Tomato",
        "category": "Fresh Produce",
        "standard_moisture_percent": 94.5,
        "standard_fat_percent": 0.2,
        "standard_ph": 4.3,
        "oxygen_sensitivity": "LOW",
        "moisture_sensitivity": "MEDIUM",
        "light_sensitivity": "LOW",
        "typical_storage_type": "Refrigerated",
        "is_fresh_produce": True,
        "respiration_category": "MODERATE",
        "map_suitable": True,
        "recommended_gas_mix": "3-5% O2, 2-3% CO2, balance N2 to retard ripening and softening",
        "source_name": "UC Davis Postharvest Technology Center",
        "source_url": "https://postharvest.ucdavis.edu/Commodity_Resources/Fact_Sheets/Datastores/Vegetables_English/?rec=36",
        "source_reference": "UC Davis Produce Fact Sheet: Tomato",
        "source_citation": "UC Davis Postharvest Technology Center - Tomato Fact Sheet",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "name": "Apple",
        "category": "Fresh Produce",
        "standard_moisture_percent": 85.5,
        "standard_fat_percent": 0.2,
        "standard_ph": 3.6,
        "oxygen_sensitivity": "LOW",
        "moisture_sensitivity": "LOW",
        "light_sensitivity": "LOW",
        "typical_storage_type": "Refrigerated",
        "is_fresh_produce": True,
        "respiration_category": "LOW",
        "map_suitable": True,
        "recommended_gas_mix": "1-2% O2, 1-2% CO2, balance N2 for controlled atmosphere storage",
        "source_name": "UC Davis Postharvest Technology Center",
        "source_url": "https://postharvest.ucdavis.edu/Commodity_Resources/Fact_Sheets/Datastores/Fruit_English/?rec=4",
        "source_reference": "UC Davis Produce Fact Sheet: Apple",
        "source_citation": "UC Davis Postharvest Technology Center - Apple Fact Sheet",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "name": "Banana",
        "category": "Fresh Produce",
        "standard_moisture_percent": 75.0,
        "standard_fat_percent": 0.3,
        "standard_ph": 5.0,
        "oxygen_sensitivity": "LOW",
        "moisture_sensitivity": "MEDIUM",
        "light_sensitivity": "LOW",
        "typical_storage_type": "Ambient",
        "is_fresh_produce": True,
        "respiration_category": "MODERATE",
        "map_suitable": True,
        "recommended_gas_mix": "2-5% O2, 2-5% CO2, balance N2 with ethylene scrubber",
        "source_name": "UC Davis Postharvest Technology Center",
        "source_url": "https://postharvest.ucdavis.edu/Commodity_Resources/Fact_Sheets/Datastores/Fruit_English/?rec=5",
        "source_reference": "UC Davis Produce Fact Sheet: Banana",
        "source_citation": "UC Davis Postharvest Technology Center - Banana Fact Sheet",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "name": "Mango",
        "category": "Fresh Produce",
        "standard_moisture_percent": 83.5,
        "standard_fat_percent": 0.4,
        "standard_ph": 4.2,
        "oxygen_sensitivity": "LOW",
        "moisture_sensitivity": "MEDIUM",
        "light_sensitivity": "LOW",
        "typical_storage_type": "Ambient",
        "is_fresh_produce": True,
        "respiration_category": "MODERATE",
        "map_suitable": True,
        "recommended_gas_mix": "3-5% O2, 5-8% CO2, balance N2 to delay ripening and anthracnose",
        "source_name": "UC Davis Postharvest Technology Center",
        "source_url": "https://postharvest.ucdavis.edu/Commodity_Resources/Fact_Sheets/Datastores/Fruit_English/?rec=24",
        "source_reference": "UC Davis Produce Fact Sheet: Mango",
        "source_citation": "UC Davis Postharvest Technology Center - Mango Fact Sheet",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "name": "Strawberry",
        "category": "Fresh Produce",
        "standard_moisture_percent": 91.0,
        "standard_fat_percent": 0.3,
        "standard_ph": 3.5,
        "oxygen_sensitivity": "LOW",
        "moisture_sensitivity": "HIGH",
        "light_sensitivity": "LOW",
        "typical_storage_type": "Refrigerated",
        "is_fresh_produce": True,
        "respiration_category": "HIGH",
        "map_suitable": True,
        "recommended_gas_mix": "3-5% O2, 10-15% CO2, balance N2 to retard mold growth and respiration",
        "source_name": "UC Davis Postharvest Technology Center",
        "source_url": "https://postharvest.ucdavis.edu/Commodity_Resources/Fact_Sheets/Datastores/Fruit_English/?rec=34",
        "source_reference": "UC Davis Produce Fact Sheet: Strawberry",
        "source_citation": "UC Davis Postharvest Technology Center - Strawberry Produce Fact Sheet",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "name": "Potato",
        "category": "Fresh Produce / Tubers",
        "standard_moisture_percent": 79.0,
        "standard_fat_percent": 0.1,
        "standard_ph": 6.0,
        "oxygen_sensitivity": "LOW",
        "moisture_sensitivity": "LOW",
        "light_sensitivity": "HIGH",
        "typical_storage_type": "Ambient",
        "is_fresh_produce": True,
        "respiration_category": "LOW",
        "map_suitable": False,
        "recommended_gas_mix": "Well-ventilated light-blocking packaging to prevent greening and condensation rot",
        "source_name": "FAO Postharvest & Agribusiness Bulletin",
        "source_url": "https://www.fao.org/post-harvest-compendium/en/",
        "source_reference": "FAO Post-harvest compendium: Root and Tuber crops",
        "source_citation": "FAO Agricultural Services Bulletin: Root and Tuber Storage",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "name": "Onion",
        "category": "Fresh Produce / Alliums",
        "standard_moisture_percent": 89.0,
        "standard_fat_percent": 0.1,
        "standard_ph": 5.6,
        "oxygen_sensitivity": "LOW",
        "moisture_sensitivity": "HIGH",
        "light_sensitivity": "LOW",
        "typical_storage_type": "Ambient",
        "is_fresh_produce": True,
        "respiration_category": "LOW",
        "map_suitable": False,
        "recommended_gas_mix": "Open mesh or breathable perforated wrap; avoid airtight packaging",
        "source_name": "UC Davis Postharvest Technology Center",
        "source_url": "https://postharvest.ucdavis.edu/Commodity_Resources/Fact_Sheets/Datastores/Vegetables_English/?rec=26",
        "source_reference": "UC Davis Produce Fact Sheet: Onion",
        "source_citation": "UC Davis Postharvest Technology Center - Onion Fact Sheet",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "name": "Carrot",
        "category": "Fresh Produce / Roots",
        "standard_moisture_percent": 88.0,
        "standard_fat_percent": 0.2,
        "standard_ph": 6.0,
        "oxygen_sensitivity": "LOW",
        "moisture_sensitivity": "MEDIUM",
        "light_sensitivity": "LOW",
        "typical_storage_type": "Refrigerated",
        "is_fresh_produce": True,
        "respiration_category": "MODERATE",
        "map_suitable": True,
        "recommended_gas_mix": "2-5% O2, 2-5% CO2, balance N2 to preserve crispness",
        "source_name": "UC Davis Postharvest Technology Center",
        "source_url": "https://postharvest.ucdavis.edu/Commodity_Resources/Fact_Sheets/Datastores/Vegetables_English/?rec=8",
        "source_reference": "UC Davis Produce Fact Sheet: Carrot",
        "source_citation": "UC Davis Postharvest Technology Center - Carrot Fact Sheet",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "name": "Cabbage",
        "category": "Fresh Produce / Leafy/Cruciferous",
        "standard_moisture_percent": 92.0,
        "standard_fat_percent": 0.1,
        "standard_ph": 5.8,
        "oxygen_sensitivity": "LOW",
        "moisture_sensitivity": "MEDIUM",
        "light_sensitivity": "LOW",
        "typical_storage_type": "Refrigerated",
        "is_fresh_produce": True,
        "respiration_category": "MODERATE",
        "map_suitable": True,
        "recommended_gas_mix": "2-3% O2, 3-6% CO2, balance N2 to delay yellowing and leaf abscission",
        "source_name": "UC Davis Postharvest Technology Center",
        "source_url": "https://postharvest.ucdavis.edu/Commodity_Resources/Fact_Sheets/Datastores/Vegetables_English/?rec=7",
        "source_reference": "UC Davis Produce Fact Sheet: Cabbage",
        "source_citation": "UC Davis Postharvest Technology Center - Cabbage Fact Sheet",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    },
    {
        "name": "Cucumber",
        "category": "Fresh Produce / Cucurbits",
        "standard_moisture_percent": 95.2,
        "standard_fat_percent": 0.1,
        "standard_ph": 5.4,
        "oxygen_sensitivity": "LOW",
        "moisture_sensitivity": "MEDIUM",
        "light_sensitivity": "LOW",
        "typical_storage_type": "Refrigerated",
        "is_fresh_produce": True,
        "respiration_category": "MODERATE",
        "map_suitable": True,
        "recommended_gas_mix": "3-5% O2, 0% CO2 (cucumber is sensitive to CO2 injury > 2%), balance N2",
        "source_name": "UC Davis Postharvest Technology Center",
        "source_url": "https://postharvest.ucdavis.edu/Commodity_Resources/Fact_Sheets/Datastores/Vegetables_English/?rec=14",
        "source_reference": "UC Davis Produce Fact Sheet: Cucumber",
        "source_citation": "UC Davis Postharvest Technology Center - Cucumber Fact Sheet",
        "data_status": "DEMO DATA",
        "last_verified": "Pending Lab Audit"
    }
]

def seed_database(db: Session):
    """Seed database with default packaging materials, preset food commodities, and scientific sources."""
    # 1. Seed Data Sources
    for src in SEED_SOURCES:
        existing_src = db.query(DataSource).filter(DataSource.source_name == src["source_name"]).first()
        if not existing_src:
            db.add(DataSource(**src))
        else:
            for k, v in src.items():
                setattr(existing_src, k, v)
    db.commit()

    # 2. Seed Packaging Materials
    for mat_data in SEED_MATERIALS:
        existing = db.query(PackagingMaterial).filter(PackagingMaterial.material_code == mat_data["material_code"]).first()
        if not existing:
            db.add(PackagingMaterial(**mat_data))
        else:
            for k, v in mat_data.items():
                setattr(existing, k, v)
    db.commit()

    # 3. Seed Food Commodities
    for com_data in SEED_COMMODITIES:
        existing_com = db.query(FoodCommodity).filter(FoodCommodity.name == com_data["name"]).first()
        if not existing_com:
            db.add(FoodCommodity(**com_data))
        else:
            for k, v in com_data.items():
                setattr(existing_com, k, v)
    db.commit()
